workspace = { members = [ "examples/dyn_list","examples/simple" ] }
[package]
name = "yew_data_link"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.21.0"
